In [2]:
import torch

In [3]:
print(torch.cuda.is_available())

True


# Torch Tensor

In [4]:
#a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [5]:
#a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [6]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [7]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [8]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [9]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [10]:
print(c.mean())
print(d.mean())
print(c.std())
print(d.std())

tensor(2.5833)
tensor(2.5833, dtype=torch.float64)
tensor(1.5050)
tensor(1.5050, dtype=torch.float64)


In [11]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-0.2518,  0.8527, -1.2990,  0.4185],
         [ 0.4029,  0.6257,  0.7812, -0.0944],
         [ 0.4710, -0.7540, -0.9044,  0.9292]],

        [[ 1.2673,  1.3341,  0.5795, -0.6090],
         [ 1.2232,  0.2181,  0.7280, -0.3801],
         [-0.9091, -0.0421, -0.3124, -1.5690]]])
tensor([[-0.2518,  0.8527, -1.2990,  0.4185,  0.4029,  0.6257,  0.7812, -0.0944,
          0.4710, -0.7540, -0.9044,  0.9292],
        [ 1.2673,  1.3341,  0.5795, -0.6090,  1.2232,  0.2181,  0.7280, -0.3801,
         -0.9091, -0.0421, -0.3124, -1.5690]])
tensor([[-0.2518,  0.8527, -1.2990,  0.4185,  0.4029

In [12]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

tensor([[0.0524, 0.5758, 0.9112, 0.8519],
        [0.6783, 0.9036, 0.5752, 0.3801],
        [0.1099, 0.8351, 0.8846, 0.5059],
        [0.6898, 0.6596, 0.1615, 0.7844]])
tensor([[ 0.5061, -1.8419, -1.5286,  1.3946],
        [-0.0483,  0.6908,  0.2102, -0.0650],
        [-0.3215,  1.4048,  0.2471,  0.7032],
        [ 0.8687,  0.5166, -1.1188, -0.8690]])
torch.float32
tensor([7, 6, 6, 7, 8])
torch.int64
tensor([[6, 7, 6],
        [6, 7, 9],
        [8, 6, 7]])
5
9


In [13]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [14]:
# Convert the data type of the tensor
r2_like = torch.randn_like(r2, dtype=torch.double)    
print(r2_like)

tensor([[ 1.4023,  0.0860,  0.9151,  1.1625],
        [-1.8757,  0.4983,  0.4577, -0.1633],
        [-0.4114, -0.9031, -1.5316,  0.1171],
        [ 1.3866,  0.6981, -0.8364, -0.6244]], dtype=torch.float64)


In [15]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 0.5585, -1.2661, -0.6174,  2.2464],
        [ 0.6300,  1.5944,  0.7854,  0.3151],
        [-0.2116,  2.2399,  1.1317,  1.2091],
        [ 1.5585,  1.1763, -0.9572, -0.0845]])


In [16]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[ 0.5585, -1.2661, -0.6174,  2.2464],
        [ 0.6300,  1.5944,  0.7854,  0.3151],
        [-0.2116,  2.2399,  1.1317,  1.2091],
        [ 1.5585,  1.1763, -0.9572, -0.0845]])


In [17]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([-1.2661,  1.5944,  2.2399,  1.1763])
tensor([[ 0.5585, -1.2661],
        [ 0.6300,  1.5944],
        [-0.2116,  2.2399],
        [ 1.5585,  1.1763]])
tensor([[ 0.5585, -1.2661, -0.6174,  2.2464],
        [ 0.6300,  1.5944,  0.7854,  0.3151],
        [-0.2116,  2.2399,  1.1317,  1.2091]])
tensor(1.2091)
1.209093689918518
tensor([-0.2116,  2.2399,  1.1317,  1.2091])


# Numpy Bridge

In [18]:
import numpy as np

In [19]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[ 0.5585, -1.2661, -0.6174,  2.2464],
        [ 0.6300,  1.5944,  0.7854,  0.3151],
        [-0.2116,  2.2399,  1.1317,  1.2091],
        [ 1.5585,  1.1763, -0.9572, -0.0845]], device='cuda:0')


In [22]:
#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[ 0.5585, -1.2661, -0.6174,  2.2464],
        [ 0.6300,  1.5944,  0.7854,  0.3151],
        [-0.2116,  2.2399,  1.1317,  1.2091],
        [ 1.5585,  1.1763, -0.9572, -0.0845]], device='cuda:0')


In [23]:
#check GPU availbility
print(torch.cuda.is_available())

True


In [24]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


# Tensor Concatenation级联(cascade)

In [25]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 0.7179, -0.3382, -0.4826, -0.4087, -0.6645],
        [ 1.9086, -0.5087,  0.7678,  0.7565,  1.3642]])
tensor([[ 1.3916, -1.5752,  1.1647, -0.2752, -0.0299],
        [ 0.9772,  0.6597, -0.1390,  0.4705, -0.6328],
        [-1.5943, -0.1398, -1.0726,  1.1649, -0.4324]])


tensor([[ 0.7179, -0.3382, -0.4826, -0.4087, -0.6645],
        [ 1.9086, -0.5087,  0.7678,  0.7565,  1.3642],
        [ 1.3916, -1.5752,  1.1647, -0.2752, -0.0299],
        [ 0.9772,  0.6597, -0.1390,  0.4705, -0.6328],
        [-1.5943, -0.1398, -1.0726,  1.1649, -0.4324]])


tensor([[ 0.0871, -0.1439,  2.3481],
        [ 0.0142,  1.1119,  0.9677]])
tensor([[ 0.4519, -1.6813,  1.8516,  0.9906,  0.1649],
        [ 0.3567, -1.2019,  0.6856,  1.4133,  0.8712]])


tensor([[ 0.0871, -0.1439,  2.3481,  0.4519, -1.6813,  1.8516,  0.9906,  0.1649],
        [ 0.0142,  1.1119,  0.9677,  0.3567, -1.2019,  0.6856,  1.4133,  0.8712]])




# AutoGrad

In [ ]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

In [ ]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

In [ ]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

In [ ]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

In [ ]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)