In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5,5)

In [4]:
layer.weight.data

tensor([[-0.0888,  0.3282, -0.3794,  0.0686, -0.1051],
        [-0.1203,  0.2929, -0.2788,  0.3856,  0.2305],
        [-0.0089, -0.0147, -0.1996, -0.0761,  0.1752],
        [ 0.1478, -0.1916,  0.2793,  0.3563,  0.3904],
        [-0.1817,  0.1955, -0.1993, -0.0479, -0.1956]])

In [6]:
#uniform distribution
#(tensor, a is min, b is max)
nn.init.uniform_(layer.weight, a=0.0, b=3)

Parameter containing:
tensor([[2.4338, 1.2873, 2.4032, 1.1603, 2.5707],
        [0.1562, 1.5276, 0.5545, 1.0950, 2.0847],
        [0.9376, 1.6683, 1.9920, 0.0425, 0.2635],
        [0.9497, 1.6827, 1.7198, 0.3852, 1.1586],
        [1.6971, 1.7008, 1.1033, 0.2779, 0.0305]], requires_grad=True)

In [7]:
#normal distribution
#(tensor, mean, std)
nn.init.normal_(layer.weight, mean=0.0, std=0.5)

Parameter containing:
tensor([[-0.3808,  0.6306,  0.0491, -0.1978,  0.2614],
        [-0.5568, -0.0219, -0.6416, -0.7672, -0.2513],
        [-0.4382,  0.2078,  0.8395, -0.3327,  0.5288],
        [ 0.4157,  0.2764,  0.1136,  0.7683, -0.1049],
        [-0.1920, -0.1702, -0.0754, -0.4851, -0.8333]], requires_grad=True)

In [8]:
#initial weight to same value is bad, but usefult to set bias
nn.init.constant_(layer.bias, 0)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [9]:
#xavier uniform distribution
#(tensor, gain)
nn.init.xavier_uniform_(layer.weight, gain = 1)

Parameter containing:
tensor([[-0.1357,  0.3773, -0.1733,  0.3408, -0.2389],
        [-0.1007, -0.6984,  0.5085, -0.6718,  0.7643],
        [ 0.6508, -0.4674,  0.7485,  0.6875, -0.6609],
        [ 0.4875, -0.7619, -0.4741, -0.5186, -0.2062],
        [-0.1188,  0.1270,  0.5629,  0.6645,  0.4466]], requires_grad=True)